# Generated by Django 4.2.8 on 2023-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeid', models.IntegerField()),
                ('name', models.TextField()),
                ('url_link', models.URLField(default='https://blob:https://imgur.com/0')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('abilities', models.JSONField()),
                ('types', models.JSONField()),
                ('moves', models.JSONField()),
                ('stats', models.JSONField()),
                ('sprites', models.JSONField()),
                ('base_experience', models.SmallIntegerField()),
            ],
        ),
    ]
