# Generated by Django 5.0.1 on 2024-01-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeid', models.IntegerField()),
                ('name', models.TextField()),
                ('url_link', models.URLField(default='https://blob:https://imgur.com/0')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('abilities', models.JSONField()),
                ('types', models.JSONField()),
                ('moves', models.JSONField()),
                ('stats', models.JSONField()),
                ('sprites', models.JSONField()),
                ('base_experience', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(max_length=151, to='pokedex_app.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(max_length=6, to='pokedex_app.pokemon')),
            ],
        ),
    ]
